translation/src/main/scala/org/opencypher/gremlin/translation/CypherAst.scala
translation/src/main/scala/org/opencypher/gremlin/translation/ir/rewrite/FilterStepAdjacency.scala
translation/src/main/scala/org/opencypher/gremlin/translation/ir/rewrite/Rewriting.scala
translation/src/test/java/org/opencypher/gremlin/translation/ir/rewrite/FilterStepAdjacencyTest.java
translation/src/test/scala/org/opencypher/gremlin/translation/ir/rewrite/RewritingTest.scala

WHERE predicate relocation should now also handle shadowed step labels.

Rewrite WHERE predicates separately by projection

---

testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/CastTest.java
translation/src/main/scala/org/opencypher/gremlin/translation/ir/rewrite/GroupStepFilters.scala
translation/src/main/scala/org/opencypher/gremlin/translation/ir/rewrite/RemoveImmediateReselect.scala
translation/src/main/scala/org/opencypher/gremlin/translation/ir/rewrite/RemoveUnusedAliases.scala
translation/src/main/scala/org/opencypher/gremlin/translation/translator/TranslatorFlavor.scala
translation/src/test/java/org/opencypher/gremlin/translation/helpers/CypherAstAssert.java
translation/src/test/java/org/opencypher/gremlin/translation/ir/rewrite/GroupStepFiltersTest.java
translation/src/test/java/org/opencypher/gremlin/translation/ir/rewrite/RemoveImmediateReselectTest.java
translation/src/test/java/org/opencypher/gremlin/translation/ir/rewrite/RemoveUnusedAliasesTest.java

Adds two rewriting optimizations:
- Removes immediate `select` after `as` with the same step label
- Removes various cases of `as` steps with unused step labels
See added Scaladoc for more details.

Remove unused aliases

---

testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/PercentileTest.java
testware/tck/src/test/scala/org/opencypher/gremlin/tck/GremlinErrors.scala
translation/src/main/java/org/opencypher/gremlin/traversal/CustomFunction.java
translation/src/main/scala/org/opencypher/gremlin/translation/walker/ProjectionWalker.scala

I don't know what I'm doing. :dog:
+12 TCK

Percentile functions

---

testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/ListComprehensionTest.java
testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/ReturnTest.java
translation/src/main/scala/org/opencypher/gremlin/translation/ir/rewrite/RemoveUselessSteps.scala
translation/src/main/scala/org/opencypher/gremlin/translation/translator/TranslatorFlavor.scala
translation/src/main/scala/org/opencypher/gremlin/translation/walker/ExpressionWalker.scala
translation/src/main/scala/org/opencypher/gremlin/translation/walker/ProjectionWalker.scala
translation/src/main/scala/org/opencypher/gremlin/translation/walker/UnwindWalker.scala
translation/src/main/scala/org/opencypher/gremlin/translation/walker/WhereWalker.scala
translation/src/test/java/org/opencypher/gremlin/translation/helpers/CypherAstAssert.java
translation/src/test/java/org/opencypher/gremlin/translation/helpers/ScalaHelpers.java
translation/src/test/java/org/opencypher/gremlin/translation/ir/rewrite/CosmosDbFlavorTest.java
translation/src/test/java/org/opencypher/gremlin/translation/ir/rewrite/RemoveUselessStepsTest.java

Evaluable expression node processing has been extracted to `ExpressionWalker`. This walker can be re-used in other contexts where expression AST nodes are found, except for expressions in predicates (e.g. `WhereWalker`, currently).
`ExpressionWalker` has only been applied in `RETURN` and `UNWIND` translations, but more should follow.
+1 TCK

Expression walker

---

testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/ContainerIndexTest.java
testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/CreateTest.java
testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/DeleteTest.java
testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/LiteralTest.java
testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/NativeTraversalTest.java
testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/ReturnTest.java
testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/SetTest.java
testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/WithTest.java
translation/src/main/java/org/opencypher/gremlin/translation/groovy/StringTranslationUtils.java
translation/src/main/java/org/opencypher/gremlin/traversal/CustomFunction.java
translation/src/main/scala/org/opencypher/gremlin/translation/CypherAst.scala
translation/src/main/scala/org/opencypher/gremlin/translation/context/StatementContext.scala
translation/src/main/scala/org/opencypher/gremlin/translation/ir/rewrite/SimplifyPropertySetters.scala
translation/src/main/scala/org/opencypher/gremlin/translation/walker/CreateWalker.scala
translation/src/main/scala/org/opencypher/gremlin/translation/walker/DeleteWalker.scala
translation/src/main/scala/org/opencypher/gremlin/translation/walker/ExpressionWalker.scala
translation/src/main/scala/org/opencypher/gremlin/translation/walker/NodeUtils.scala
translation/src/test/java/org/opencypher/gremlin/translation/helpers/CypherAstHelpers.java
translation/src/test/java/org/opencypher/gremlin/translation/ir/rewrite/GroupStepFiltersTest.java
translation/src/test/java/org/opencypher/gremlin/translation/ir/rewrite/SimplifyPropertySettersTest.java

Experimental implementation of list and map literals as Gremlin projections.
- Allows to translate every individual collection item as an expression.
- Empty maps are inlined as instances of `LinkedHashMap`.
- Includes a related change to `DELETE` translation that now delegates to `ExpressionWalker` (TCK tests for `DELETE` depend on this collection translation).
Let's give this some thought before actually merging.
+19 TCK

Model collection literals as projections

---

translation/src/main/scala/org/opencypher/gremlin/translation/CypherAst.scala
translation/src/test/java/org/opencypher/gremlin/translation/ir/rewrite/GroupStepFiltersTest.java

- Variables created in `nameAllPatternElements` and other rewriters should appear in `state.semantics().typeTable`
- As in `frontend.phases.CompilationPhases`, `SemanticAnalysis` should run twice

Run SemanticAnalysis before&after Normalization

---

testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/VariableLengthPathTest.java
translation/src/main/java/org/opencypher/gremlin/translation/GremlinSteps.java
translation/src/main/java/org/opencypher/gremlin/translation/Tokens.java
translation/src/main/java/org/opencypher/gremlin/translation/bytecode/BytecodeGremlinSteps.java
translation/src/main/java/org/opencypher/gremlin/translation/groovy/GroovyGremlinSteps.java
translation/src/main/java/org/opencypher/gremlin/translation/traversal/TraversalGremlinSteps.java
translation/src/main/scala/org/opencypher/gremlin/translation/context/StatementContext.scala
translation/src/main/scala/org/opencypher/gremlin/translation/ir/TranslationWriter.scala
translation/src/main/scala/org/opencypher/gremlin/translation/ir/builder/IRGremlinSteps.scala
translation/src/main/scala/org/opencypher/gremlin/translation/ir/model/GremlinStep.scala
translation/src/main/scala/org/opencypher/gremlin/translation/walker/CallWalker.scala
translation/src/main/scala/org/opencypher/gremlin/translation/walker/MatchWalker.scala
translation/src/main/scala/org/opencypher/gremlin/translation/walker/MergeWalker.scala
translation/src/main/scala/org/opencypher/gremlin/translation/walker/NodeUtils.scala
translation/src/main/scala/org/opencypher/gremlin/translation/walker/PatternWalker.scala
translation/src/main/scala/org/opencypher/gremlin/translation/walker/ProjectionWalker.scala
translation/src/main/scala/org/opencypher/gremlin/translation/walker/StatementWalker.scala
translation/src/main/scala/org/opencypher/gremlin/translation/walker/UnwindWalker.scala
translation/src/test/java/org/opencypher/gremlin/translation/ir/rewrite/InlineMapTraversalTest.java

TCK +3
- Avoid loops
- Fix for multiple relationships

Var length path refactoring

---

testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/WhereTest.java
translation/src/main/scala/org/opencypher/gremlin/translation/ir/rewrite/RemoveUselessSteps.scala
translation/src/main/scala/org/opencypher/gremlin/translation/ir/rewrite/SimplifyRenamedAliases.scala
translation/src/main/scala/org/opencypher/gremlin/translation/translator/TranslatorFlavor.scala
translation/src/main/scala/org/opencypher/gremlin/translation/walker/ExpressionWalker.scala
translation/src/main/scala/org/opencypher/gremlin/translation/walker/MatchWalker.scala
translation/src/main/scala/org/opencypher/gremlin/translation/walker/PatternWalker.scala
translation/src/main/scala/org/opencypher/gremlin/translation/walker/ProjectionWalker.scala
translation/src/main/scala/org/opencypher/gremlin/translation/walker/WhereWalker.scala
translation/src/test/java/org/opencypher/gremlin/translation/ir/rewrite/SimplifyRenamedAliases.java

- Covers cases like `WHERE (:L)--(n)`
- Adds rewrite rule to simplify alias renames in the beginning of match patterns to `.select()`
- Adds rewrite rule for accidental `.as(x).as(x)`

Support alias reuse in WHERE patterns

---

testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/CastTest.java
testware/integration-tests/src/test/java/org/opencypher/gremlin/traversal/ReturnNormalizerTest.java
translation/src/main/java/org/opencypher/gremlin/traversal/CustomFunction.java
translation/src/main/java/org/opencypher/gremlin/traversal/ReturnNormalizer.java
translation/src/main/scala/org/opencypher/gremlin/translation/walker/ExpressionWalker.scala

- Integer typecasts now try converting to long first, before converting to double's long value
- If a returned value is typed as integer, but is not numeric, it is now returned as is

Return original value if cannot be normalized as integer

---

testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/ReturnTest.java
translation/src/main/scala/org/opencypher/gremlin/translation/ir/rewrite/RemoveUnusedAliases.scala
translation/src/main/scala/org/opencypher/gremlin/translation/ir/rewrite/RemoveUselessSteps.scala
translation/src/main/scala/org/opencypher/gremlin/translation/ir/rewrite/SimplifySingleProjections.scala
translation/src/main/scala/org/opencypher/gremlin/translation/walker/ExpressionWalker.scala
translation/src/main/scala/org/opencypher/gremlin/translation/walker/NodeUtils.scala
translation/src/test/scala/org/opencypher/gremlin/translation/ir/rewrite/RemoveUnusedAliasesTest.scala

This rewrite lifts traversals from single projections that start with a fold. This helps other rewriters to detect cases like `fold().unfold()`, greatly simplifying some projections.
`coalesce`-based null guards have been replaced with `choose`-based, because of unexpected behavior of global `coalesce` in some TCK corner cases.
Unused alias removal has been fixed to not skip adjacent `as` steps.

Lift traversal out of folding projections

---

testware/integration-tests/src/test/java/org/opencypher/gremlin/client/BytecodeCypherGremlinClientTest.java
testware/integration-tests/src/test/java/org/opencypher/gremlin/client/GroovyCypherGremlinClientTest.java
tinkerpop/cypher-gremlin-server-client/src/main/java/org/opencypher/gremlin/client/BytecodeCypherGremlinClient.java
translation/src/main/java/org/opencypher/gremlin/translation/GroovyIdentifiers.java
translation/src/main/java/org/opencypher/gremlin/translation/bytecode/BytecodeGremlinBindings.java
translation/src/main/java/org/opencypher/gremlin/translation/groovy/GroovyGremlinBindings.java

Also applies the same validation to bytecode translation, since it can be converted to Groovy on Gremlin Server.

Fail on keywords used as parameters for Groovy translation

---

build.gradle
translation/src/main/scala/org/opencypher/gremlin/translation/CypherAst.scala
translation/src/main/scala/org/opencypher/gremlin/translation/Normalization.scala
translation/src/main/scala/org/opencypher/gremlin/translation/walker/ProjectionWalker.scala
translation/src/test/java/org/opencypher/gremlin/translation/AstRewriterTest.java

These changes remove the `projectFreshSortExpressions` rewriter, which in turn:
- Removes identity projections produced by this rewriter
- Will help to migrate to new FE with changes from https://github.com/opencypher/front-end/pull/21.

Remove reliance on projectFreshSortExpressions

---

testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/FunctionTest.java
translation/src/main/java/org/opencypher/gremlin/translation/GremlinSteps.java
translation/src/main/java/org/opencypher/gremlin/translation/bytecode/BytecodeGremlinSteps.java
translation/src/main/java/org/opencypher/gremlin/translation/groovy/GroovyGremlinSteps.java
translation/src/main/java/org/opencypher/gremlin/translation/traversal/TraversalGremlinSteps.java
translation/src/main/scala/org/opencypher/gremlin/translation/ir/TranslationWriter.scala
translation/src/main/scala/org/opencypher/gremlin/translation/ir/builder/IRGremlinSteps.scala
translation/src/main/scala/org/opencypher/gremlin/translation/ir/model/GremlinStep.scala
translation/src/main/scala/org/opencypher/gremlin/translation/walker/ExpressionWalker.scala

Basic implementation of Cypher `head()` function

---

translation/src/main/java/org/opencypher/gremlin/translation/translator/Translator.java
translation/src/main/java/org/opencypher/gremlin/traversal/CustomFunction.java
translation/src/main/scala/org/opencypher/gremlin/translation/ir/rewrite/CustomFunctionFallback.scala
translation/src/main/scala/org/opencypher/gremlin/translation/translator/TranslatorFlavor.scala
translation/src/test/scala/org/opencypher/gremlin/translation/ir/rewrite/CustomFunctionsFallbackTest.scala

Always use `CustomFunctionsFallback` if Cypher Extensions are not enable.

Use `CustomFunctionsFallback` if  Extensions are not enabled

---

translation/src/main/scala/org/opencypher/gremlin/translation/ir/rewrite/CustomFunctionFallback.scala
translation/src/test/java/org/opencypher/gremlin/translation/CypherAstTest.java
translation/src/test/scala/org/opencypher/gremlin/translation/ir/rewrite/CustomFunctionsFallbackTest.scala
translation/src/test/scala/org/opencypher/gremlin/translation/ir/verify/NoCustomFunctionsTest.scala

- cypherSize - treat input as collection if type information and extensions are not available
- cypherProperties - treat input as element if type information and extensions are not available
- +2 TCK on Native

Custom functions cypherProperties and cypherSize fallback (#160)

---

testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/ListComprehensionTest.java
tinkerpop/cypher-gremlin-extensions/src/main/java/org/opencypher/gremlin/traversal/CustomFunctions.java
translation/src/main/java/org/opencypher/gremlin/traversal/CustomFunction.java
translation/src/main/scala/org/opencypher/gremlin/translation/CypherAst.scala
translation/src/main/scala/org/opencypher/gremlin/translation/context/WalkerContext.scala
translation/src/main/scala/org/opencypher/gremlin/translation/translator/TranslatorFlavor.scala
translation/src/main/scala/org/opencypher/gremlin/translation/walker/ExpressionWalker.scala
translation/src/main/scala/org/opencypher/gremlin/translation/walker/NodeUtils.scala
translation/src/main/scala/org/opencypher/gremlin/translation/walker/ProjectionWalker.scala

* Native implementation of path comprehension
* More correct rewrite of list comprehension without sideEffect
* Consistent List normalization in final projection
* Remove returnTypes Context (as duplicate of expressionTypes)
* Fix conflicting rewriter order
* +3 TCK
* +7 TCK without extensions

Pattern comprehension improvements

---

testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/DeleteTest.java
testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/NativeTraversalTest.java
testware/tck/src/test/scala/org/opencypher/gremlin/tck/GremlinErrors.scala
tinkerpop/cypher-gremlin-extensions/src/main/java/org/opencypher/gremlin/translation/exception/EntityNotFound.java
translation/src/main/scala/org/opencypher/gremlin/translation/walker/ProjectionWalker.scala
translation/src/main/scala/org/opencypher/gremlin/translation/walker/StatementWalker.scala

- Don't allow aggregates in aggregates
- Don't allow non deterministic functions in aggregates
- Don't access properties or labels of deleted items
- TCK mappings for errors above
TCK +5

Add validations

---

translation/src/main/scala/org/opencypher/gremlin/translation/ir/rewrite/GroupStepFilters.scala
translation/src/main/scala/org/opencypher/gremlin/translation/walker/CreateWalker.scala
translation/src/test/scala/org/opencypher/gremlin/translation/ir/rewrite/GroupStepFiltersTest.scala

- Fix bug with GroupStepFilters rewriter when condition is applied to `addV` step instead of `V` step
- TCK +2

Support named path creation

---

translation/src/main/java/org/opencypher/gremlin/translation/ReturnProperties.java
translation/src/main/scala/org/opencypher/gremlin/translation/walker/CreateWalker.scala
translation/src/main/scala/org/opencypher/gremlin/translation/walker/ExpressionWalker.scala
translation/src/main/scala/org/opencypher/gremlin/translation/walker/MatchWalker.scala

- Fix missing variable select in PatternComprehension
- Fix converter allowing path with duplicate nodes
- Fix possibility of duplicated nodes in MatchWalker
- Reuse MatchWalker in named path creation
- TCK +1

Chain of related fixes

---

build.gradle
translation/src/main/scala/org/opencypher/gremlin/translation/ir/rewrite/RemoveIntermediateProjection.scala
translation/src/main/scala/org/opencypher/gremlin/translation/translator/TranslatorFlavor.scala
translation/src/main/scala/org/opencypher/gremlin/translation/walker/ProjectionWalker.scala
translation/src/test/java/org/opencypher/gremlin/translation/AstRewriterTest.java
translation/src/test/scala/org/opencypher/gremlin/translation/ir/rewrite/RemoveIntermediateProjectionTest.scala

- Upgrade to frontend `9.0.2018091`
- Since 9.0.8 front-end removes `normalizeReturnClauses` which created intermediate projection for ORDER, LIMIT e.t.c
- Intermediate projection is now created in CfoG translation
- Finalization moved to separate projection
- Rewriter that removes multiple projections if not necessary

Upgrade to latest FE

---

testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/FunctionTest.java
testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/ReturnTest.java
tinkerpop/cypher-gremlin-extensions/src/main/java/org/opencypher/gremlin/traversal/CustomFunctions.java
translation/src/main/scala/org/opencypher/gremlin/translation/ir/TranslationWriter.scala
translation/src/main/scala/org/opencypher/gremlin/translation/ir/builder/IRGremlinSteps.scala
translation/src/main/scala/org/opencypher/gremlin/translation/ir/model/GremlinStep.scala
translation/src/main/scala/org/opencypher/gremlin/translation/ir/rewrite/CustomFunctionFallback.scala
translation/src/main/scala/org/opencypher/gremlin/translation/ir/rewrite/RemoveUselessNullChecks.scala
translation/src/main/scala/org/opencypher/gremlin/translation/ir/rewrite/SimplifyDelete.scala
translation/src/main/scala/org/opencypher/gremlin/translation/ir/rewrite/SimplifyPropertySetters.scala
translation/src/main/scala/org/opencypher/gremlin/translation/walker/ExpressionWalker.scala
translation/src/main/scala/org/opencypher/gremlin/translation/walker/NodeUtils.scala
translation/src/main/scala/org/opencypher/gremlin/translation/walker/ProjectionWalker.scala
translation/src/test/scala/org/opencypher/gremlin/translation/ir/rewrite/CustomFunctionsFallbackTest.scala
translation/src/test/scala/org/opencypher/gremlin/translation/ir/rewrite/RemoveUselessNullChecksTest.scala

- Omit unnecessary `_.constant(NULL)` in null guards:
- `choose(p.neq(NULL), traversal, constant(NULL))` → `choose(p.neq(NULL), traversal)`
- Use `NodeUtils#notNull` in projection walker
- Skip null checks in gremlin steps that handle `  cypher.null`: `limit`, `tail`, `range`, `identity`
- More tests for nulls

Simplify null guards

---

translation/src/main/scala/org/opencypher/gremlin/translation/ir/rewrite/SimplifySingleProjections.scala
translation/src/main/scala/org/opencypher/gremlin/translation/walker/ExpressionWalker.scala
translation/src/test/scala/org/opencypher/gremlin/translation/ir/rewrite/RemoveUselessStepsTest.scala

- `fold()` loses traversal history (e.g. `g.V().as('a').fold().select('a')` returns noting)
- In cases where `fold()` is used for collection creation, replaced with `map(fold())` (e.g. `g.V().as('a').map(fold()).select('a')`)
- Fix `SimplifySingleProjections` rewriter removing valid re-`select`
TCK +2

Fixed related bugs with `fold` and rewriting

---

testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/ReturnTest.java
tinkerpop/cypher-gremlin-extensions/src/main/java/org/opencypher/gremlin/translation/Tokens.java
tinkerpop/cypher-gremlin-extensions/src/main/java/org/opencypher/gremlin/traversal/CustomPredicate.java
translation/src/main/java/org/opencypher/gremlin/translation/GremlinPredicates.java
translation/src/main/java/org/opencypher/gremlin/translation/bytecode/BytecodeGremlinPredicates.java
translation/src/main/java/org/opencypher/gremlin/translation/groovy/GroovyGremlinPredicates.java
translation/src/main/java/org/opencypher/gremlin/translation/translator/Translator.java
translation/src/main/java/org/opencypher/gremlin/translation/traversal/TraversalGremlinPredicates.java
translation/src/main/scala/org/opencypher/gremlin/translation/ir/TranslationWriter.scala
translation/src/main/scala/org/opencypher/gremlin/translation/ir/builder/IRGremlinPredicates.scala
translation/src/main/scala/org/opencypher/gremlin/translation/ir/model/GremlinPredicate.scala
translation/src/main/scala/org/opencypher/gremlin/translation/ir/rewrite/CustomFunctionFallback.scala
translation/src/main/scala/org/opencypher/gremlin/translation/ir/rewrite/RemoveUnusedAliases.scala
translation/src/main/scala/org/opencypher/gremlin/translation/walker/ExpressionWalker.scala
translation/src/main/scala/org/opencypher/gremlin/translation/walker/ProjectionWalker.scala
translation/src/test/scala/org/opencypher/gremlin/translation/ir/rewrite/CustomFunctionFallbackTest.scala

- `nodes` and `relationship` functions to use "  cypher.path.edge." side effect collection
- Fix returning multiple lists of elements in multiple rows
TCK +1

`nodes` and `relationship` fixes

---

testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/WithTest.java
translation/src/main/scala/org/opencypher/gremlin/translation/context/WalkerContext.scala
translation/src/main/scala/org/opencypher/gremlin/translation/walker/ProjectionWalker.scala

- When selecting alias not defined in `WITH` don't match aliases defined before `WITH`
- Clear aliases before rebinding in `reselectProjection`
TCK +1

Only aliases in `WITH` are bound:

---

translation/src/main/scala/org/opencypher/gremlin/translation/ir/TranslationWriter.scala
translation/src/main/scala/org/opencypher/gremlin/translation/ir/builder/IRGremlinSteps.scala
translation/src/main/scala/org/opencypher/gremlin/translation/ir/model/GremlinStep.scala
translation/src/main/scala/org/opencypher/gremlin/translation/ir/rewrite/CosmosDbFlavor.scala
translation/src/main/scala/org/opencypher/gremlin/translation/ir/rewrite/CustomFunctionFallback.scala
translation/src/main/scala/org/opencypher/gremlin/translation/ir/rewrite/RemoveUselessNullChecks.scala
translation/src/main/scala/org/opencypher/gremlin/translation/ir/rewrite/SimplifyDelete.scala
translation/src/main/scala/org/opencypher/gremlin/translation/ir/rewrite/SimplifyPropertySetters.scala
translation/src/main/scala/org/opencypher/gremlin/translation/ir/verify/NoCustomFunctions.scala
translation/src/test/scala/org/opencypher/gremlin/translation/ir/rewrite/CosmosDbFlavorTest.scala
translation/src/test/scala/org/opencypher/gremlin/translation/ir/rewrite/NeptuneFlavorTest.scala

- Rewrite `choose(a, b)` → `choose(a, b, identity()`
- In TinkerPop 3.3.4 order `desc`/`incr` deprecated in favor of `asc`/`desc`. Because its not available in Cosmos DB - fallback to deprecated values

Cosmos DB improvements

---

translation/src/main/scala/org/opencypher/gremlin/translation/ir/rewrite/CosmosDbFlavor.scala
translation/src/main/scala/org/opencypher/gremlin/translation/ir/rewrite/NeptuneFlavor.scala
translation/src/main/scala/org/opencypher/gremlin/translation/walker/ProjectionWalker.scala
translation/src/test/scala/org/opencypher/gremlin/translation/ir/rewrite/CosmosDbFlavorTest.scala
translation/src/test/scala/org/opencypher/gremlin/translation/ir/rewrite/NeptuneFlavorTest.scala

- Keep deprecated `desc`/`incr` while all backends (JanusGraph, CosmosDB, Neptune) have not upgraded to TinkerPop 3.3.4

Rollback to deprecated `desc`/`incr` values.

---

translation/src/main/scala/org/opencypher/gremlin/translation/ir/rewrite/NeptuneFlavor.scala
translation/src/test/scala/org/opencypher/gremlin/translation/ir/rewrite/NeptuneFlavorTest.scala

Remove `g.inject(0)` -> `g.V().limit(0).inject(0)` workaround for Neptune

---

translation/src/main/java/org/opencypher/gremlin/translation/groovy/StringTranslationUtils.java

- `.property('float_prop',1.4)` → `.property('float_prop', 1.4d)`
- https://github.com/JanusGraph/janusgraph/issues/487

Improve compatibility by adding type to float properties in GremlinGroovy

---

testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/WhereTest.java
translation/src/main/scala/org/opencypher/gremlin/translation/walker/WhereWalker.scala

- Avoid creating inmemory list, when its possible to pass arguments as varargs
- Simplifies rewriter task for #227

Cleaner `without`/`within` predicate translation

---

testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/NullTest.java
tinkerpop/cypher-gremlin-extensions/src/main/java/org/opencypher/gremlin/traversal/CustomPredicate.java
translation/src/main/java/org/opencypher/gremlin/translation/GremlinPredicates.java
translation/src/main/java/org/opencypher/gremlin/translation/bytecode/BytecodeGremlinPredicates.java
translation/src/main/java/org/opencypher/gremlin/translation/groovy/GroovyGremlinPredicates.java
translation/src/main/java/org/opencypher/gremlin/translation/traversal/TraversalGremlinPredicates.java
translation/src/main/scala/org/opencypher/gremlin/translation/ir/TranslationWriter.scala
translation/src/main/scala/org/opencypher/gremlin/translation/ir/builder/IRGremlinPredicates.scala
translation/src/main/scala/org/opencypher/gremlin/translation/ir/model/GremlinPredicate.scala
translation/src/main/scala/org/opencypher/gremlin/translation/ir/rewrite/RemoveUnusedAliases.scala
translation/src/main/scala/org/opencypher/gremlin/translation/walker/ExpressionWalker.scala
translation/src/main/scala/org/opencypher/gremlin/translation/walker/ProjectionWalker.scala
translation/src/test/java/org/opencypher/gremlin/traversal/CustomPredicateTest.java

- Additional predicate to check string type
- Return NULL in wrong predicate type
- Fix bug when string predicates were not recognized as `WHERE` conditions
- Merge changes from #191
TCK +3

Consider type in predicates:

---

README.md
testware/integration-tests/src/test/resources/snippets/console-demo.out

Improve README

---

testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/QueryTimeoutTest.java
testware/testware-common/src/main/java/org/opencypher/gremlin/server/EmbeddedGremlinServer.java
tinkerpop/cypher-gremlin-server-plugin/src/main/java/org/opencypher/gremlin/server/op/cypher/CypherOpProcessor.java

- to be consistent with `TraversalOpProcessor` and `AbstractEvalOpProcessor`
- part of #315

Make `CypherOpProcessor` handle `scriptEvaluationTimeout`

---

testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/SpecificsTest.java
translation/src/main/scala/org/opencypher/gremlin/translation/ir/rewrite/CosmosDbFlavor.scala
translation/src/test/scala/org/opencypher/gremlin/translation/ir/rewrite/CosmosDbFlavorTest.scala

- Workaround to address recent change in Cosmos DB, where traversal ending at `.barrier().limit(0)` was not evaluated
- Updated tests according to recent changes in Cosmos DB
- fixes #314

Workaround for CREATE without RETURN in Cosmos DB
