testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/ComplexExamplesTest.java, translation/src/main/java/org/opencypher/gremlin/translation/Tokens.java, translation/src/main/scala/org/opencypher/gremlin/translation/walker/WhereWalker.scala, translation/src/test/java/org/opencypher/gremlin/translation/MatchTest.java
=> RHS improvements

testware/tck/src/test/scala/org/opencypher/gremlin/tck/TckGremlinCypherValueConverter.scala, testware/tck/src/test/scala/org/opencypher/gremlin/tck/TckTest.scala
=> Possibility to run single TCK scenario or feature

testware/integration-tests/src/test/java/org/opencypher/gremlin/neo4jadapter/GremlinNeo4jDriverTest.java, tinkerpop/cypher-gremlin-neo4j-driver/src/main/java/org/opencypher/GremlinServerDriver.java
=> Fix SerializationException when passing map with parameters

translation/src/main/java/org/opencypher/gremlin/traversal/ReturnNormalizer.java
=> Descriptive error in case of wrong serializer

testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/ReturnTest.java, translation/src/main/java/org/opencypher/gremlin/traversal/CustomFunction.java, translation/src/main/scala/org/opencypher/gremlin/translation/walker/ProjectionWalker.scala
=> Implementation for 'properties'

testware/tck/src/test/scala/org/opencypher/gremlin/tck/GremlinErrors.scala, translation/src/main/java/org/opencypher/gremlin/traversal/ReturnNormalizer.java
=> Corrected quotes in TCK error message patterns

tinkerpop/cypher-gremlin-console-plugin/README.md, tinkerpop/cypher-gremlin-neo4j-driver/README.md, tinkerpop/cypher-gremlin-server-client/README.md, tinkerpop/cypher-gremlin-server-plugin/README.md, translation/README.md
=> Release 0.9.4

testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/UnwindTest.java, translation/src/main/scala/org/opencypher/gremlin/translation/walker/UnwindWalker.scala
=> UNWIND keys() translation

build.gradle, testware/tck/src/test/scala/org/opencypher/gremlin/tck/GremlinQueries.scala
=> Upgrade tck-api to `tck-api:1.0.0-M10`

translation/src/main/scala/org/opencypher/gremlin/translation/walker/ProjectionWalker.scala
- Fail in `ProjectionWalker` instead of `ReturnNormalizer`
- Show cause instead of `Unable to convert result v[13]`
=> Fail fast on unsupported expression

testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/NativeTraversalTest.java, translation/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/MathStepAcessor.java, translation/src/main/java/org/opencypher/gremlin/translation/GremlinSteps.java, translation/src/main/java/org/opencypher/gremlin/translation/bytecode/BytecodeGremlinSteps.java, translation/src/main/java/org/opencypher/gremlin/translation/groovy/GroovyGremlinSteps.java, translation/src/main/java/org/opencypher/gremlin/translation/traversal/TraversalGremlinSteps.java, translation/src/main/java/org/opencypher/gremlin/traversal/CustomFunction.java, translation/src/main/java/org/opencypher/gremlin/traversal/ReturnNormalizer.java, translation/src/main/scala/org/opencypher/gremlin/translation/CypherAst.scala, translation/src/main/scala/org/opencypher/gremlin/translation/ir/TranslationWriter.scala, translation/src/main/scala/org/opencypher/gremlin/translation/ir/builder/IRGremlinSteps.scala, translation/src/main/scala/org/opencypher/gremlin/translation/ir/model/GremlinStep.scala, translation/src/main/scala/org/opencypher/gremlin/translation/ir/rewrite/RemoveUnusedAliases.scala, translation/src/main/scala/org/opencypher/gremlin/translation/walker/ProjectionWalker.scala, translation/src/test/java/org/opencypher/gremlin/translation/CypherAstWrapperTest.java
=> Support Math expressions in return

testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/VariableLengthPathTest.java, translation/src/main/java/org/opencypher/gremlin/traversal/CustomFunction.java, translation/src/main/java/org/opencypher/gremlin/traversal/ReturnNormalizer.java, translation/src/main/scala/org/opencypher/gremlin/translation/walker/ProjectionWalker.scala
- Proper handling of `ListType` return types
- Consistent normalization of both traversal and custom function elements
=> Show issues hidden by `Unable to convert result...` exception

testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/CreateTest.java, testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/NullTest.java, testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/SetTest.java, translation/src/main/scala/org/opencypher/gremlin/translation/ir/rewrite/SimplifyPropertySetters.scala, translation/src/main/scala/org/opencypher/gremlin/translation/translator/TranslatorFlavor.scala, translation/src/main/scala/org/opencypher/gremlin/translation/walker/CreateWalker.scala, translation/src/main/scala/org/opencypher/gremlin/translation/walker/ExpressionWalker.scala, translation/src/main/scala/org/opencypher/gremlin/translation/walker/NodeUtils.scala, translation/src/main/scala/org/opencypher/gremlin/translation/walker/SetWalker.scala, translation/src/test/java/org/opencypher/gremlin/translation/helpers/CypherAstHelpers.java, translation/src/test/java/org/opencypher/gremlin/translation/ir/rewrite/GroupStepFiltersTest.java, translation/src/test/java/org/opencypher/gremlin/translation/ir/rewrite/SimplifyPropertySettersTest.java
Re-use `ExpressionWalker` in `CREATE`, `SET`, and `REMOVE`.
+3 TCK
=> Re-use expression walker in writing clauses

build.gradle
=> Run Cucumber report with TCK task only

translation/src/main/scala/org/opencypher/gremlin/translation/ir/rewrite/ProjectionSimplifications.scala, translation/src/main/scala/org/opencypher/gremlin/translation/translator/TranslatorFlavor.scala, translation/src/test/java/org/opencypher/gremlin/translation/ir/rewrite/ProjectionSimplificationsTest.java
- Remove select in case of single key and Tokens.UNUSED workaround
=> Projection Simplifications rewriter

translation/src/main/scala/org/opencypher/gremlin/translation/ir/rewrite/ProjectionSimplifications.scala
=> Fix TCK regression

tinkerpop/cypher-gremlin-console-plugin/README.md, tinkerpop/cypher-gremlin-neo4j-driver/README.md, tinkerpop/cypher-gremlin-server-client/README.md, tinkerpop/cypher-gremlin-server-client/src/main/java/org/opencypher/gremlin/client/TraverserIterator.java, tinkerpop/cypher-gremlin-server-plugin/README.md, translation/README.md
=> Release 0.9.5

translation/src/main/java/org/opencypher/gremlin/translation/GremlinSteps.java, translation/src/main/java/org/opencypher/gremlin/translation/bytecode/BytecodeGremlinSteps.java, translation/src/main/java/org/opencypher/gremlin/translation/groovy/GroovyGremlinSteps.java, translation/src/main/java/org/opencypher/gremlin/translation/traversal/TraversalGremlinSteps.java, translation/src/main/java/org/opencypher/gremlin/traversal/CustomFunction.java, translation/src/main/scala/org/opencypher/gremlin/translation/ir/TranslationWriter.scala, translation/src/main/scala/org/opencypher/gremlin/translation/ir/builder/IRGremlinSteps.scala, translation/src/main/scala/org/opencypher/gremlin/translation/ir/model/GremlinStep.scala, translation/src/main/scala/org/opencypher/gremlin/translation/walker/ExpressionWalker.scala
=> Gremlin translation of ContainerIndex

testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/ReturnTest.java, translation/src/main/scala/org/opencypher/gremlin/translation/CypherAst.scala, translation/src/main/scala/org/opencypher/gremlin/translation/walker/ExpressionWalker.scala
- Handle any expressions in property access left-hand side
- Treat property access with unknown type as map type
+3 TCK
=> Handle any expressions in property access left-hand side

testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/CastTest.java, translation/src/main/java/org/opencypher/gremlin/traversal/CustomFunction.java
=> Throw on invalid string casts

testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/ReturnTest.java, translation/src/main/java/org/opencypher/gremlin/traversal/CustomFunction.java, translation/src/main/scala/org/opencypher/gremlin/translation/walker/ExpressionWalker.scala
=> Plus operator overloads for strings and lists

testware/tck/src/test/scala/org/opencypher/gremlin/tck/GremlinErrors.scala
=> Map TCK false negative errors

testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/ContainerIndexTest.java, testware/tck/src/test/scala/org/opencypher/gremlin/tck/GremlinErrors.scala, translation/src/main/java/org/opencypher/gremlin/traversal/CustomFunction.java, translation/src/main/scala/org/opencypher/gremlin/translation/walker/ExpressionWalker.scala, translation/src/main/scala/org/opencypher/gremlin/translation/walker/ProjectionWalker.scala
=> Custom function fallback for container index

testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/ExpressionTest.java, testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/ReturnTest.java, translation/src/main/java/org/opencypher/gremlin/traversal/ParameterNormalizer.java, translation/src/main/scala/org/opencypher/gremlin/translation/walker/ExpressionWalker.scala, translation/src/main/scala/org/opencypher/gremlin/translation/walker/NodeUtils.scala, translation/src/test/java/org/opencypher/gremlin/translation/ir/rewrite/SimplifyPropertySettersTest.java
Also includes a null guard for parameters.
+4 TCK
=> Comparison expressions

testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/ExpressionTest.java, tinkerpop/cypher-gremlin-server-client/src/main/java/org/opencypher/gremlin/client/BytecodeCypherGremlinClient.java, tinkerpop/cypher-gremlin-server-client/src/main/java/org/opencypher/gremlin/client/GroovyCypherGremlinClient.java, tinkerpop/cypher-gremlin-server-client/src/main/java/org/opencypher/gremlin/client/InMemoryCypherGremlinClient.java, tinkerpop/cypher-gremlin-server-plugin/src/main/java/org/opencypher/gremlin/server/op/cypher/CypherOpProcessor.java, translation/src/main/java/org/opencypher/gremlin/translation/CypherAstWrapper.java, translation/src/main/java/org/opencypher/gremlin/translation/bytecode/BytecodeGremlinPredicates.java, translation/src/main/java/org/opencypher/gremlin/traversal/ParameterNormalizer.java, translation/src/main/scala/org/opencypher/gremlin/translation/CypherAst.scala, translation/src/main/scala/org/opencypher/gremlin/translation/walker/ExpressionWalker.scala, translation/src/test/java/org/opencypher/gremlin/translation/CypherAstWrapperTest.java
- Support IN in any expression
- Fix within/without bytecode translation
- Remove extracted parameters API
- Normalize query parameters in clients and plugin
+9 TCK
=> IN expressions

build.gradle
=> Exclude TinkerPop classes from server plugin jar

testware/integration-tests/src/test/java/org/opencypher/gremlin/console/GremlinConsoleTest.java, tinkerpop/cypher-gremlin-console-plugin/src/main/java/org/opencypher/gremlin/console/jsr223/CypherRemoteAcceptor.java
=> Support `:remote console`, closes #4

build.gradle
=> Exclude transitive test dependencies

testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/ContainerIndexTest.java, testware/tck/src/test/scala/org/opencypher/gremlin/tck/GremlinErrors.scala, translation/src/main/java/org/opencypher/gremlin/traversal/CustomFunction.java, translation/src/main/scala/org/opencypher/gremlin/translation/walker/ExpressionWalker.scala, translation/src/main/scala/org/opencypher/gremlin/translation/walker/WhereWalker.scala
=>  Fallback on custom container index in property access

testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/ComplexExamplesTest.java, translation/src/main/java/org/opencypher/gremlin/translation/GremlinSteps.java, translation/src/main/java/org/opencypher/gremlin/translation/bytecode/BytecodeGremlinSteps.java, translation/src/main/java/org/opencypher/gremlin/translation/groovy/GroovyGremlinSteps.java, translation/src/main/java/org/opencypher/gremlin/translation/traversal/TraversalGremlinSteps.java, translation/src/main/scala/org/opencypher/gremlin/translation/ir/TranslationWriter.scala, translation/src/main/scala/org/opencypher/gremlin/translation/ir/builder/IRGremlinSteps.scala, translation/src/main/scala/org/opencypher/gremlin/translation/ir/model/GremlinStep.scala, translation/src/main/scala/org/opencypher/gremlin/translation/ir/rewrite/RemoveUnusedAliases.scala, translation/src/main/scala/org/opencypher/gremlin/translation/walker/MatchWalker.scala, translation/src/main/scala/org/opencypher/gremlin/translation/walker/RelationshipPatternWalker.scala
=> Deduplicate paths in MATCH with undirected relationship

translation/src/main/scala/org/opencypher/gremlin/translation/walker/ProjectionWalker.scala
=> Return null if path is null

testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/CreateTest.java, testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/OptionalMatchTest.java, testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/WithTest.java
=> Test improvements

testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/ComplexExamplesTest.java, testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/CreateTest.java, testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/MergeTest.java, translation/src/main/java/org/opencypher/gremlin/translation/traversal/TraversalGremlinSteps.java, translation/src/main/scala/org/opencypher/gremlin/translation/ir/verify/NoEmptyTraversals.scala, translation/src/main/scala/org/opencypher/gremlin/translation/translator/TranslatorFlavor.scala, translation/src/main/scala/org/opencypher/gremlin/translation/walker/MatchWalker.scala, translation/src/main/scala/org/opencypher/gremlin/translation/walker/MergeWalker.scala, translation/src/main/scala/org/opencypher/gremlin/translation/walker/NodeUtils.scala
=> MERGE improvements

build.gradle, testware/testware-common/src/main/java/org/opencypher/gremlin/rules/GremlinServerExternalResource.java, tinkerpop/cypher-gremlin-console-plugin/src/main/java/org/opencypher/gremlin/console/jsr223/CypherRemoteAcceptor.java, translation/src/main/scala/org/opencypher/gremlin/translation/ir/rewrite/NeptuneFlavor.scala, translation/src/main/scala/org/opencypher/gremlin/translation/translator/TranslatorFlavor.scala
=> Introduce AWS Neptune Flavor

testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/FunctionTest.java, translation/src/main/scala/org/opencypher/gremlin/translation/walker/ExpressionWalker.scala
=> Add native translation of size(list) function

testware/testware-common/src/main/java/org/opencypher/gremlin/rules/GremlinServerExternalResource.java
=> Test target improvements

testware/tck/src/test/scala/org/opencypher/gremlin/tck/TckGremlinCypherValueConverter.scala, testware/testware-common/src/main/java/org/opencypher/gremlin/rules/GremlinServerExternalResource.java, translation/src/main/java/org/opencypher/gremlin/traversal/ReturnNormalizer.java
- Universal id handling
- Universal exception handling
- Gremlin Groovy translation without Cypher Translations
=> TCK improvements

testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/FunctionTest.java, translation/src/main/scala/org/opencypher/gremlin/translation/walker/ExpressionWalker.scala
=> Translation of size(pattern expression)

translation/src/main/java/org/opencypher/gremlin/translation/GremlinSteps.java, translation/src/main/java/org/opencypher/gremlin/translation/bytecode/BytecodeGremlinSteps.java, translation/src/main/java/org/opencypher/gremlin/translation/groovy/GroovyGremlinSteps.java, translation/src/main/java/org/opencypher/gremlin/translation/traversal/TraversalGremlinSteps.java, translation/src/main/scala/org/opencypher/gremlin/translation/ir/TranslationWriter.scala, translation/src/main/scala/org/opencypher/gremlin/translation/ir/builder/IRGremlinSteps.scala, translation/src/main/scala/org/opencypher/gremlin/translation/ir/model/GremlinStep.scala, translation/src/main/scala/org/opencypher/gremlin/translation/ir/rewrite/NeptuneFlavor.scala, translation/src/main/scala/org/opencypher/gremlin/translation/ir/rewrite/SimplifyPropertySetters.scala, translation/src/main/scala/org/opencypher/gremlin/translation/walker/CreateWalker.scala, translation/src/main/scala/org/opencypher/gremlin/translation/walker/ExpressionWalker.scala, translation/src/main/scala/org/opencypher/gremlin/translation/walker/NodeUtils.scala, translation/src/main/scala/org/opencypher/gremlin/translation/walker/SetWalker.scala, translation/src/test/scala/org/opencypher/gremlin/translation/ir/CardinalityTest.scala, translation/src/test/scala/org/opencypher/gremlin/translation/ir/helpers/CypherAstAssert.scala, translation/src/test/scala/org/opencypher/gremlin/translation/ir/rewrite/NeptuneFlavorTest.scala, translation/src/test/scala/org/opencypher/gremlin/translation/ir/rewrite/SimplifyPropertySettersTest.scala
=> Use cardinality = single for vertex properties

testware/testware-common/src/main/resources/logback.xml
=> Log Gremlin

testware/integration-tests/src/test/java/org/opencypher/gremlin/neo4jadapter/GremlinNeo4jDriverTest.java, testware/integration-tests/src/test/java/org/opencypher/gremlin/snippets/CypherGremlinNeo4jDriverSnippets.java, testware/testware-common/src/main/resources/tinkergraph-empty.properties, tinkerpop/cypher-gremlin-neo4j-driver/README.md, tinkerpop/cypher-gremlin-neo4j-driver/src/main/java/org/opencypher/gremlin/neo4j/driver/Config.java, tinkerpop/cypher-gremlin-neo4j-driver/src/main/java/org/opencypher/gremlin/neo4j/driver/GremlinCypherValueConverter.java, tinkerpop/cypher-gremlin-neo4j-driver/src/main/java/org/opencypher/gremlin/neo4j/driver/GremlinGraphDriver.java, tinkerpop/cypher-gremlin-neo4j-driver/src/main/java/org/opencypher/gremlin/neo4j/driver/GremlinServerDriver.java, tinkerpop/cypher-gremlin-neo4j-driver/src/main/java/org/opencypher/gremlin/neo4j/driver/GremlinServerSession.java, tinkerpop/cypher-gremlin-neo4j-driver/src/main/java/org/opencypher/gremlin/neo4j/driver/GremlinServerStatementResult.java, tinkerpop/cypher-gremlin-neo4j-driver/src/test/java/org/opencypher/gremlin/neo4j/driver/GremlinServerStatementResultTest.java
=> Allow to ignore ids in Neo4j driver for better compatibility

build.gradle, testware/tck/src/test/java/org/opencypher/gremlin/tck/reports/OpenCypherTckReport.java
As graphs are located on project page.
=> TCK report should only contain detailed coverage info

translation/src/main/scala/org/opencypher/gremlin/translation/ir/TraversalHelper.scala, translation/src/main/scala/org/opencypher/gremlin/translation/ir/rewrite/GroupStepFilters.scala, translation/src/main/scala/org/opencypher/gremlin/translation/ir/rewrite/SimplifyRenamedAliases.scala, translation/src/test/scala/org/opencypher/gremlin/translation/ir/TraversalHelperTest.scala
=> `splitAfter(splitter)` → `split( BeforeStep/AfterStep, splitter)`

tinkerpop/cypher-gremlin-extensions/src/main/java/org/opencypher/gremlin/translation/Tokens.java, translation/src/main/scala/org/opencypher/gremlin/translation/context/NameGenerator.scala, translation/src/main/scala/org/opencypher/gremlin/translation/ir/rewrite/RemoveMultipleAliases.scala, translation/src/main/scala/org/opencypher/gremlin/translation/translator/TranslatorFlavor.scala, translation/src/test/scala/org/opencypher/gremlin/translation/ir/helpers/CypherAstAssertions.scala, translation/src/test/scala/org/opencypher/gremlin/translation/ir/helpers/TraversalAssertions.scala, translation/src/test/scala/org/opencypher/gremlin/translation/ir/rewrite/GroupStepFiltersTest.scala, translation/src/test/scala/org/opencypher/gremlin/translation/ir/rewrite/RemoveMultipleAliasesTest.scala, translation/src/test/scala/org/opencypher/gremlin/translation/ir/rewrite/RemoveUnusedAliasesTest.scala, translation/src/test/scala/org/opencypher/gremlin/translation/ir/rewrite/SimplifyRenamedAliasesTest.scala
=> Multiple Aliases Rewriter

tinkerpop/cypher-gremlin-console-plugin/README.md, tinkerpop/cypher-gremlin-neo4j-driver/README.md, tinkerpop/cypher-gremlin-server-client/README.md, tinkerpop/cypher-gremlin-server-plugin/README.md, translation/README.md
=> Release 0.9.11

.circleci/config.yml
=> Retrigger CircleCI

build.gradle
=> Update FE to 9.0.7

translation/src/main/scala/org/opencypher/gremlin/translation/ir/rewrite/CustomFunctionFallback.scala, translation/src/test/scala/org/opencypher/gremlin/translation/ir/rewrite/CustomFunctionsFallbackTest.scala
Custom function `cypherPlus` fallback 
- Fallback to arithmetic `sum()` if type information and extensions are not available
- +4 TCK on Native/Neptune
=> Custom function cypherPlus fallback 

testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/CaseTest.java, translation/src/main/java/org/opencypher/gremlin/translation/GremlinSteps.java, translation/src/main/java/org/opencypher/gremlin/translation/bytecode/BytecodeGremlinSteps.java, translation/src/main/java/org/opencypher/gremlin/translation/groovy/GroovyGremlinSteps.java, translation/src/main/java/org/opencypher/gremlin/translation/traversal/TraversalGremlinSteps.java, translation/src/main/scala/org/opencypher/gremlin/translation/ir/TranslationWriter.scala, translation/src/main/scala/org/opencypher/gremlin/translation/ir/builder/IRGremlinSteps.scala, translation/src/main/scala/org/opencypher/gremlin/translation/ir/model/GremlinStep.scala, translation/src/main/scala/org/opencypher/gremlin/translation/ir/rewrite/SimplifySingleProjections.scala, translation/src/main/scala/org/opencypher/gremlin/translation/walker/ExpressionWalker.scala
=> Support of CASE expression

.circleci/config.yml
=> More memory for builds

.circleci/config.yml, build.gradle
=> Try to fix builds

testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/SetTest.java, translation/src/main/scala/org/opencypher/gremlin/translation/walker/NodeUtils.scala, translation/src/main/scala/org/opencypher/gremlin/translation/walker/SetWalker.scala
=> Support parameters in `SetPropertiesFromMapItem`

build.gradle, testware/tck/README.md, testware/tck/src/test/scala/org/opencypher/gremlin/tck/TckTest.scala
=> TCK Parameter to ignore scenarios from file

translation/src/main/scala/org/opencypher/gremlin/translation/walker/ProjectionWalker.scala
=> Refactoring: remove exceptions as control flow

testware/tck/README.md
=> Documentation for TCK tools

testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/RangeTest.java, testware/tck/src/test/scala/org/opencypher/gremlin/tck/GremlinErrors.scala, tinkerpop/cypher-gremlin-extensions/src/main/java/org/opencypher/gremlin/translation/exception/ArgumentException.java, translation/src/main/scala/org/opencypher/gremlin/translation/ir/rewrite/CosmosDbFlavor.scala, translation/src/main/scala/org/opencypher/gremlin/translation/walker/DeleteWalker.scala, translation/src/main/scala/org/opencypher/gremlin/translation/walker/ExpressionWalker.scala, translation/src/main/scala/org/opencypher/gremlin/translation/walker/NodeUtils.scala, translation/src/test/scala/org/opencypher/gremlin/translation/ir/rewrite/CosmosDbFlavorTest.scala
=> Support expressions in `range()`

testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/FunctionTest.java, tinkerpop/cypher-gremlin-extensions/src/main/java/org/opencypher/gremlin/traversal/CustomFunctions.java, translation/src/main/java/org/opencypher/gremlin/traversal/CustomFunction.java, translation/src/main/scala/org/opencypher/gremlin/translation/walker/ExpressionWalker.scala
- `endnode`
- `startnode`
- `reverse`
- `split`
- `substring`
- `toupper`
- `tolower`
TCK +5
=> Implemented missing Cypher functions:

build.gradle
=> Upgrade to latest FE

testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/ReturnTest.java, translation/src/main/scala/org/opencypher/gremlin/translation/walker/ExpressionWalker.scala, translation/src/main/scala/org/opencypher/gremlin/translation/walker/PatternWalker.scala, translation/src/main/scala/org/opencypher/gremlin/translation/walker/ProjectionWalker.scala
- Refactor finalization of element lists
- Support nested lists
- Don't start new traversal inside pattern comprehension
TCK +2
=> Pattern comprehension improvements

testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/RangeTest.java, translation/src/main/scala/org/opencypher/gremlin/translation/ir/rewrite/CosmosDbFlavor.scala, translation/src/main/scala/org/opencypher/gremlin/translation/walker/ExpressionWalker.scala
=> Bug: Keep traversal history when using `RANGE`

testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/ReturnTest.java, testware/testware-common/src/main/java/org/opencypher/gremlin/test/TestCommons.java, tinkerpop/cypher-gremlin-extensions/src/main/java/org/opencypher/gremlin/translation/Tokens.java, translation/src/main/scala/org/opencypher/gremlin/translation/ir/rewrite/CustomFunctionFallback.scala, translation/src/main/scala/org/opencypher/gremlin/translation/walker/ExpressionWalker.scala, translation/src/test/scala/org/opencypher/gremlin/translation/ir/rewrite/CustomFunctionFallbackTest.scala
=> Simplify `nodes()` and `relationships` functions

testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/SetTest.java, tinkerpop/cypher-gremlin-extensions/src/main/java/org/opencypher/gremlin/traversal/CustomFunctions.java, translation/src/main/java/org/opencypher/gremlin/traversal/CustomFunction.java, translation/src/main/scala/org/opencypher/gremlin/translation/walker/ExpressionWalker.scala, translation/src/main/scala/org/opencypher/gremlin/translation/walker/NodeUtils.scala, translation/src/main/scala/org/opencypher/gremlin/translation/walker/SetWalker.scala
=> Custom function to copy properties between elements

testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/VariableLengthPathTest.java, translation/src/main/java/org/opencypher/gremlin/translation/GremlinSteps.java, translation/src/main/java/org/opencypher/gremlin/translation/bytecode/BytecodeGremlinSteps.java, translation/src/main/java/org/opencypher/gremlin/translation/groovy/GroovyGremlinSteps.java, translation/src/main/java/org/opencypher/gremlin/translation/traversal/TraversalGremlinSteps.java, translation/src/main/scala/org/opencypher/gremlin/translation/ir/TranslationWriter.scala, translation/src/main/scala/org/opencypher/gremlin/translation/ir/builder/IRGremlinSteps.scala, translation/src/main/scala/org/opencypher/gremlin/translation/ir/model/GremlinStep.scala, translation/src/main/scala/org/opencypher/gremlin/translation/ir/rewrite/RemoveUnusedAliases.scala, translation/src/main/scala/org/opencypher/gremlin/translation/walker/ExpressionWalker.scala, translation/src/main/scala/org/opencypher/gremlin/translation/walker/MatchWalker.scala, translation/src/main/scala/org/opencypher/gremlin/translation/walker/NodeUtils.scala, translation/src/main/scala/org/opencypher/gremlin/translation/walker/ProjectionWalker.scala
=> Return List<Relationship> instead of Relationship on var length paths

testware/integration-tests/src/test/java/org/opencypher/gremlin/console/GremlinConsoleTest.java
=> Reenable GremlinConsoleTest

build.gradle
=> Pass `configPath` to integration-tests

build.gradle, testware/integration-tests/src/test/java/org/opencypher/gremlin/groups/WithCustomFunctions.java, testware/integration-tests/src/test/java/org/opencypher/gremlin/groups/WithCustomPredicates.java, testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/CastTest.java, testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/ComplexExamplesTest.java, testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/ContainerIndexTest.java, testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/DeleteTest.java, testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/ExpressionTest.java, testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/FunctionTest.java, testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/ListComprehensionTest.java, testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/ListSliceTest.java, testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/NativeTraversalTest.java, testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/ParameterTest.java, testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/PercentileTest.java, testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/ReturnTest.java, testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/SetTest.java, testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/WhereTest.java
Categorize integration tests that require custom functions or predicates to run
=> Categorize integration tests

translation/src/main/scala/org/opencypher/gremlin/translation/ir/rewrite/CosmosDbFlavor.scala, translation/src/test/scala/org/opencypher/gremlin/translation/ir/rewrite/CosmosDbFlavorTest.scala
- Rewrite `skip` → `range`
- Convert ids to String
=> Cosmos DB improvements II

translation/src/main/scala/org/opencypher/gremlin/translation/ir/rewrite/GroupStepFilters.scala, translation/src/test/scala/org/opencypher/gremlin/translation/ir/rewrite/GroupStepFiltersTest.scala
I try fix that issue https://github.com/opencypher/cypher-for-gremlin/issues/223
Query like that
```
MATCH (n)
WHERE id(n) in [1, 2]
RETURN n
MATCH (n)
WHERE id(n) = 1
RETURN n
```
may translate to:
```
g.V().has('~id', within(1, 2))...
g.V().has('~id', 1)...
```
=> Rewrite where with id

testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/FunctionTest.java
=> Couple of tests for functions

testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/CaseTest.java, translation/src/main/scala/org/opencypher/gremlin/translation/walker/ExpressionWalker.scala, translation/src/main/scala/org/opencypher/gremlin/translation/walker/NodeUtils.scala, translation/src/main/scala/org/opencypher/gremlin/translation/walker/WhereWalker.scala
=> Expressions as pick tokens in simple `CASE` form

testware/README.md
=> Run integration tests on Neo4j

testware/integration-tests/src/test/java/org/opencypher/gremlin/groups/SkipWithCosmosDB.java, testware/integration-tests/src/test/java/org/opencypher/gremlin/groups/SkipWithJanusGraph.java, testware/integration-tests/src/test/java/org/opencypher/gremlin/groups/SkipWithNeptune.java, testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/CaseTest.java, testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/MatchTest.java, testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/SetTest.java, testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/SpecificsTest.java, testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/WithTest.java, testware/integration-tests/src/test/java/org/opencypher/gremlin/snippets/CypherGremlinServerClientSnippets.java, testware/testware-common/src/main/java/org/opencypher/gremlin/rules/GremlinServerExternalResource.java, tinkerpop/cypher-gremlin-server-client/README.md, tinkerpop/cypher-gremlin-server-client/src/main/java/org/opencypher/gremlin/client/CypherGremlinClient.java, tinkerpop/cypher-gremlin-server-client/src/main/java/org/opencypher/gremlin/client/SyncGroovyCypherGremlinClient.java
=> Compatibility tweaks

tinkerpop/cypher-gremlin-console-plugin/README.md, tinkerpop/cypher-gremlin-neo4j-driver/README.md, tinkerpop/cypher-gremlin-server-client/README.md, tinkerpop/cypher-gremlin-server-plugin/README.md, translation/README.md
=> Release 0.9.13

build.gradle, testware/integration-tests/src/test/java/org/opencypher/gremlin/groups/SkipWithPlugin.java, testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/GremlinFunctionTest.java, testware/integration-tests/src/test/java/org/opencypher/gremlin/snippets/CypherGremlinServerClientSnippets.java, testware/integration-tests/src/test/java/org/opencypher/gremlin/snippets/TranslationSnippets.java, testware/testware-common/src/main/java/org/opencypher/gremlin/rules/GremlinServerExternalResource.java, tinkerpop/cypher-gremlin-extensions/README.md, tinkerpop/cypher-gremlin-server-client/README.md, translation/src/main/java/org/opencypher/gremlin/translation/GremlinSteps.java, translation/src/main/java/org/opencypher/gremlin/translation/bytecode/BytecodeGremlinSteps.java, translation/src/main/java/org/opencypher/gremlin/translation/groovy/GroovyGremlinSteps.java, translation/src/main/java/org/opencypher/gremlin/translation/translator/Translator.java, translation/src/main/java/org/opencypher/gremlin/translation/translator/TranslatorFeature.java, translation/src/main/java/org/opencypher/gremlin/translation/traversal/TraversalGremlinSteps.java, translation/src/main/scala/org/opencypher/gremlin/translation/ir/GremlinParser.scala, translation/src/main/scala/org/opencypher/gremlin/translation/ir/TranslationWriter.scala, translation/src/main/scala/org/opencypher/gremlin/translation/ir/builder/IRGremlinSteps.scala, translation/src/main/scala/org/opencypher/gremlin/translation/ir/model/GremlinStep.scala, translation/src/main/scala/org/opencypher/gremlin/translation/walker/ExpressionWalker.scala, translation/src/test/scala/org/opencypher/gremlin/translation/ir/GremlinParserTest.scala, translation/src/test/scala/org/opencypher/gremlin/translation/translator/TranslatorBuilderTest.scala
- Allows including Gremlin steps in translated query
- Needs to be explicitly enabled
=> Experimental `gremlin` function

README.md, docker/cypher-gremlin-console/.gremlin_groovy_history, docker/cypher-gremlin-console/Dockerfile, docker/cypher-gremlin-console/Makefile, docker/cypher-gremlin-console/README.md, docker/cypher-gremlin-console/conf/cypher-server.yaml, docker/cypher-gremlin-console/conf/remote-graph.properties, docker/cypher-gremlin-console/plugins.txt, docker/cypher-gremlin-server/Dockerfile, docker/cypher-gremlin-server/Makefile, docker/cypher-gremlin-server/README.md, docker/cypher-gremlin-server/conf/gremlin-server-modern.yaml, tinkerpop/cypher-gremlin-console-plugin/README.md
=> Docker images

testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/FunctionTest.java, tinkerpop/cypher-gremlin-extensions/src/main/java/org/opencypher/gremlin/traversal/CustomFunctions.java, translation/src/main/java/org/opencypher/gremlin/traversal/CustomFunction.java, translation/src/main/scala/org/opencypher/gremlin/translation/walker/ExpressionWalker.scala
=> Implement `replace` function #255

build.gradle, testware/tck/src/test/java/org/opencypher/gremlin/tck/reports/CucumberReportAdapter.java, testware/tck/src/test/java/org/opencypher/gremlin/tck/reports/OpenCypherTckReport.java, testware/tck/src/test/java/org/opencypher/gremlin/tck/reports/model/TCKTestCase.java, testware/tck/src/test/java/org/opencypher/gremlin/tck/reports/model/TCKTestStep.java
- Upgrade `cucumber` to 4.2.0
- Upgrade `cucumber-reporting` to 4.5.1
=> Upgrade Cucumber

testware/integration-tests/src/test/resources/snippets/console-demo.out
=> Fix truncated lines

testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/CaseTest.java, testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/FunctionTest.java, translation/src/main/scala/org/opencypher/gremlin/translation/walker/NodeUtils.scala
=> Fix failed case expression

testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/FunctionTest.java, tinkerpop/cypher-gremlin-extensions/src/main/java/org/opencypher/gremlin/traversal/CustomPredicate.java, translation/src/main/java/org/opencypher/gremlin/translation/GremlinPredicates.java, translation/src/main/java/org/opencypher/gremlin/translation/bytecode/BytecodeGremlinPredicates.java, translation/src/main/java/org/opencypher/gremlin/translation/groovy/GroovyGremlinPredicates.java, translation/src/main/java/org/opencypher/gremlin/translation/traversal/TraversalGremlinPredicates.java, translation/src/main/scala/org/opencypher/gremlin/translation/ir/TranslationWriter.scala, translation/src/main/scala/org/opencypher/gremlin/translation/ir/builder/IRGremlinPredicates.scala, translation/src/main/scala/org/opencypher/gremlin/translation/ir/model/GremlinPredicate.scala, translation/src/main/scala/org/opencypher/gremlin/translation/ir/rewrite/RemoveMultipleAliases.scala, translation/src/main/scala/org/opencypher/gremlin/translation/ir/rewrite/RemoveUnusedAliases.scala, translation/src/main/scala/org/opencypher/gremlin/translation/walker/ExpressionWalker.scala, translation/src/main/scala/org/opencypher/gremlin/translation/walker/WhereWalker.scala
=> Regex Match

testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/SetTest.java, translation/src/main/scala/org/opencypher/gremlin/translation/walker/NodeUtils.scala, translation/src/main/scala/org/opencypher/gremlin/translation/walker/SetWalker.scala
#236
Signed-off-by: Pavel Ershov <owner.mad.epa@gmail.com>
=> Add support for SET params with array

testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/UnwindTest.java, translation/src/main/scala/org/opencypher/gremlin/translation/walker/WhereWalker.scala
=> Use `hasNot` only when testing elements.

testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/VariableLengthPathTest.java, tinkerpop/cypher-gremlin-extensions/README.md, translation/src/main/scala/org/opencypher/gremlin/translation/ir/rewrite/CosmosDbFlavor.scala, translation/src/main/scala/org/opencypher/gremlin/translation/walker/PatternWalker.scala, translation/src/test/scala/org/opencypher/gremlin/translation/ir/rewrite/RemoveMultipleAliasesTest.scala
- [Courtesy of Daniel Kuppitz](https://gist.github.com/dkuppitz/aa13783ff844e9c5016084a3286cbb0d)
=> Better translation for variable length paths

testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/CaseTest.java, translation/src/main/scala/org/opencypher/gremlin/translation/walker/ProjectionWalker.scala
=> Fix #279 empty properties in `WITH` clause

testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/SetTest.java, tinkerpop/cypher-gremlin-extensions/README.md, tinkerpop/cypher-gremlin-extensions/src/main/java/org/opencypher/gremlin/traversal/CustomFunctions.java, translation/src/main/java/org/opencypher/gremlin/translation/GremlinSteps.java, translation/src/main/java/org/opencypher/gremlin/translation/bytecode/BytecodeGremlinSteps.java, translation/src/main/java/org/opencypher/gremlin/translation/groovy/GroovyGremlinSteps.java, translation/src/main/java/org/opencypher/gremlin/translation/traversal/TraversalGremlinSteps.java, translation/src/main/java/org/opencypher/gremlin/traversal/CustomFunction.java, translation/src/main/scala/org/opencypher/gremlin/translation/ir/TranslationWriter.scala, translation/src/main/scala/org/opencypher/gremlin/translation/ir/builder/IRGremlinSteps.scala, translation/src/main/scala/org/opencypher/gremlin/translation/ir/model/GremlinStep.scala, translation/src/main/scala/org/opencypher/gremlin/translation/walker/SetWalker.scala
=> Native translation of copyProperties

README.md, tinkerpop/cypher-gremlin-console-plugin/README.md, tinkerpop/cypher-gremlin-neo4j-driver/README.md, tinkerpop/cypher-gremlin-server-client/README.md, tinkerpop/cypher-gremlin-server-plugin/README.md, translation/README.md
=> Release v1.0.1

testware/integration-tests/src/test/java/org/opencypher/gremlin/client/GroovyCypherGremlinClientTest.java, testware/integration-tests/src/test/java/org/opencypher/gremlin/console/GremlinConsoleTest.java, tinkerpop/cypher-gremlin-console-plugin/src/main/java/org/opencypher/gremlin/console/jsr223/CypherRemoteAcceptor.java
=> Fix console plugin returning multiple records

tinkerpop/cypher-gremlin-server-plugin/src/main/java/org/opencypher/gremlin/server/op/cypher/CypherOpProcessor.java, translation/src/main/java/org/opencypher/gremlin/traversal/ReturnNormalizer.java
- Avoid using lambdas in opProcessor
=> Fix subtraversals lose aliases on server translation

README.md, build.gradle, testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/UnwindTest.java, testware/integration-tests/src/test/resources/snippets/gremlin-javascript.js, tinkerpop/cypher-gremlin-server-plugin/README.md
=> Upgrade to TinkerPop 3.4.2

testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/SetTest.java
=> Fix test category

testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/ComplexExamplesTest.java, translation/src/main/scala/org/opencypher/gremlin/translation/walker/PatternWalker.scala
=> Fix dedup filtering out valid elements

README.md, tinkerpop/cypher-gremlin-console-plugin/README.md, tinkerpop/cypher-gremlin-neo4j-driver/README.md, tinkerpop/cypher-gremlin-server-client/README.md, tinkerpop/cypher-gremlin-server-plugin/README.md, translation/README.md
=> Release 1.0.2

docker/cypher-gremlin-console/Dockerfile, docker/cypher-gremlin-server/Dockerfile, docker/cypher-gremlin-server/conf/gremlin-server-modern.yaml
=> Upgrade Docker images to TinkerPop 3.4.2

README.md
=> Add JanusGraph TCK results

testware/integration-tests/src/test/java/org/opencypher/gremlin/client/CypherTraversalSourceTest.java, tinkerpop/cypher-gremlin-extensions/README.md, translation/src/main/scala/org/opencypher/gremlin/translation/ir/verify/NoCustomFunctions.scala, translation/src/test/scala/org/opencypher/gremlin/translation/ir/verify/NoCustomFunctionsTest.scala, translation/src/test/scala/org/opencypher/gremlin/translation/translator/TranslatorBuilderTest.scala
=> Clarification that `regex` is custom predicate #294

build.gradle, testware/tck/README.md, testware/tck/src/test/java/org/opencypher/gremlin/traversal/TckPredefinedProceduresPlugin.java, testware/tck/src/test/scala/org/opencypher/gremlin/tck/TckTest.scala, testware/tck/src/test/scala/org/opencypher/gremlin/traversal/GremlinQueries.scala, testware/testware-common/src/main/java/org/opencypher/gremlin/server/EmbeddedGremlinServer.java
=> Gremlin Server Plugin with TCK Predefined procedures

translation/src/main/java/org/opencypher/gremlin/translation/translator/Translator.java, translation/src/test/scala/org/opencypher/gremlin/translation/translator/TranslatorBuilderTest.scala
=> Replace runtime reflection with test phase validation by reflection

tinkerpop/cypher-gremlin-server-plugin/README.md, translation/README.md
=> JanusGraph `0.4.0` clarifications

README.md
=> Trigger rebuild.

testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/QueryTimeoutTest.java, testware/integration-tests/src/test/java/org/opencypher/gremlin/snippets/CypherGremlinServerClientSnippets.java, tinkerpop/cypher-gremlin-server-client/README.md, tinkerpop/cypher-gremlin-server-client/src/main/java/org/opencypher/gremlin/client/BytecodeCypherGremlinClient.java, tinkerpop/cypher-gremlin-server-client/src/main/java/org/opencypher/gremlin/client/CypherGremlinClient.java, tinkerpop/cypher-gremlin-server-client/src/main/java/org/opencypher/gremlin/client/CypherStatement.java, tinkerpop/cypher-gremlin-server-client/src/main/java/org/opencypher/gremlin/client/GroovyCypherGremlinClient.java, tinkerpop/cypher-gremlin-server-client/src/main/java/org/opencypher/gremlin/client/InMemoryCypherGremlinClient.java, tinkerpop/cypher-gremlin-server-client/src/main/java/org/opencypher/gremlin/client/OpProcessorCypherGremlinClient.java, tinkerpop/cypher-gremlin-server-client/src/main/java/org/opencypher/gremlin/client/SyncGroovyCypherGremlinClient.java, tinkerpop/cypher-gremlin-server-client/src/test/java/org/opencypher/gremlin/client/CypherStatementTest.java
=> Make Gremlin Timeout configurable

build.gradle, testware/integration-tests/src/test/java/org/opencypher/gremlin/client/OpProcessorGryoMessageSerializerTest.java, testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/QueryTimeoutTest.java, testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/RangeTest.java, testware/testware-common/src/main/java/org/opencypher/gremlin/server/EmbeddedGremlinServer.java, tinkerpop/cypher-gremlin-console-plugin/src/main/java/org/opencypher/gremlin/console/jsr223/CypherPlugin.java, tinkerpop/cypher-gremlin-server-client/src/main/java/org/opencypher/gremlin/client/GroovyCypherGremlinClient.java, tinkerpop/cypher-gremlin-server-client/src/main/java/org/opencypher/gremlin/client/OpProcessorCypherGremlinClient.java, tinkerpop/cypher-gremlin-server-plugin/src/main/java/org/opencypher/gremlin/server/op/cypher/CypherOpProcessor.java
- Update deprecated code
- Test to ensure that CfoG will continue working with deprecated `GryoMessageSerializer`
=> Upgrade to TinkerPop 3.4.4

.circleci/config.yml
=> Fix CircleCi

build.gradle, testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/QueryTimeoutTest.java, testware/testware-common/src/main/java/org/opencypher/gremlin/server/EmbeddedGremlinServer.java, tinkerpop/cypher-gremlin-server-client/src/main/java/org/opencypher/gremlin/client/GroovyCypherGremlinClient.java, tinkerpop/cypher-gremlin-server-client/src/main/java/org/opencypher/gremlin/client/OpProcessorCypherGremlinClient.java, tinkerpop/cypher-gremlin-server-plugin/src/main/java/org/opencypher/gremlin/server/op/cypher/CypherOpProcessor.java
- https://groups.google.com/forum/#!topic/gremlin-users/A9rr9jLh5AY
=> Downgrade to TinkerPop 3.4.3 to avoid Cosmos DB authentication issues

translation/src/main/scala/org/opencypher/gremlin/translation/ir/rewrite/GroupStepFilters.scala, translation/src/test/scala/org/opencypher/gremlin/translation/ir/rewrite/GroupStepFiltersTest.scala
=> Optimization: GroupStepFilter to handle `within`
